service: astronaut-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  astronaut:
    handler: handler.astronaut
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
